name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    env:
      # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
      xcode: '/Applications/Xcode_14.0.1.app'
      destination_ios16: 'platform=iOS Simulator,OS=16.0,name=iPhone 14'
      destination_ios15: 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CAREEVOLUTIONBUILD_TOKEN }}
          submodules: 'recursive'
      - name: Link to Older Simulators
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_13.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 15.0.simruntime
      - name: Build
        run: |
          set -o pipefail
          xcodebuild build-for-testing -workspace 'RKWorkspace.xcworkspace' -scheme 'ORK1Kit' -destination '${{ env.destination_ios15 }}' -destination '${{ env.destination_ios16 }}' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO IS_TRAVIS_CI=true | xcpretty
          xcodebuild build-for-testing -workspace 'RKWorkspace.xcworkspace' -scheme 'ResearchKit' -destination '${{ env.destination_ios15 }}' -destination '${{ env.destination_ios16 }}' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO IS_TRAVIS_CI=true | xcpretty
        env:
          DEVELOPER_DIR: ${{ env.xcode }}/Contents/Developer
      - name: Test
        run: |
          set -o pipefail
          xcodebuild test-without-building -workspace 'RKWorkspace.xcworkspace' -scheme 'ORK1Kit' -destination '${{ env.destination_ios16 }}' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO IS_TRAVIS_CI=true | xcpretty
          xcodebuild test-without-building -workspace 'RKWorkspace.xcworkspace' -scheme 'ORK1Kit' -destination '${{ env.destination_ios15 }}' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO IS_TRAVIS_CI=true | xcpretty
          xcodebuild test-without-building -workspace 'RKWorkspace.xcworkspace' -scheme 'ResearchKit' -destination '${{ env.destination_ios16 }}' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO IS_TRAVIS_CI=true | xcpretty
          xcodebuild test-without-building -workspace 'RKWorkspace.xcworkspace' -scheme 'ResearchKit' -destination '${{ env.destination_ios15 }}' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO IS_TRAVIS_CI=true | xcpretty
        env:
          DEVELOPER_DIR: ${{ env.xcode }}/Contents/Developer
