name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-26
    env:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
      xcode: '/Applications/Xcode_26.2.app'
      destination_ios: 'platform=iOS Simulator,OS=26.2,name=iPhone 17'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CAREEVOLUTIONBUILD_TOKEN }}
          submodules: 'recursive'
      - name: Build
        run: |
          set -o pipefail
          xcodebuild build-for-testing -workspace 'RKWorkspace.xcworkspace' -scheme 'ORK1Kit' -destination '${{ env.destination_ios }}' IS_TRAVIS_CI=true | xcpretty
          xcodebuild build-for-testing -workspace 'RKWorkspace.xcworkspace' -scheme 'ResearchKit' -destination '${{ env.destination_ios }}' IS_TRAVIS_CI=true | xcpretty
        env:
          DEVELOPER_DIR: ${{ env.xcode }}/Contents/Developer
      - name: Test
        run: |
          set -o pipefail
          xcodebuild test-without-building -workspace 'RKWorkspace.xcworkspace' -scheme 'ORK1Kit' -destination '${{ env.destination_ios }}' IS_TRAVIS_CI=true | xcpretty
          xcodebuild test-without-building -workspace 'RKWorkspace.xcworkspace' -scheme 'ResearchKit' -destination '${{ env.destination_ios }}' IS_TRAVIS_CI=true | xcpretty
        env:
          DEVELOPER_DIR: ${{ env.xcode }}/Contents/Developer
